'use strict';
require('dotenv').config();
const crypto=require('crypto'),fs=require('fs'),path=require('path'),mysql=require('mysql2/promise'),cookieParser=require('cookie-parser'),cors=require('cors'),express=require('express'),helmet=require('helmet'),multer=require('multer');
const ROOT=__dirname,UPLOADS=process.env.ACUITY_UPLOADS_PATH?path.resolve(process.env.ACUITY_UPLOADS_PATH):path.join(ROOT,'private_uploads'),PORT=process.env.PORT||3000,MAX_UPLOAD_BYTES=5*1024*1024,SESSION_DAYS=7,STATUSES=new Set(['PENDING','DOCUMENT_VERIFICATION','UNDER_REVIEW','APPROVED','REJECTED','DISBURSED','CLOSED']);
fs.mkdirSync(UPLOADS,{recursive:true});
const pool=mysql.createPool({host:process.env.DB_HOST,port:Number(process.env.DB_PORT)||3306,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,waitForConnections:true,connectionLimit:10,queueLimit:0,multipleStatements:true});
const query=async(sql,p=[])=>(await pool.execute(sql,p))[0],one=async(sql,p=[])=>((await query(sql,p))[0]),now=()=>new Date().toISOString(),id=p=>`${p}-${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`,appNo=()=>`AF-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}$${crypto.pbkdf2Sync(password,salt,200000,32,'sha256').toString('hex')}`;}
function verifyPassword(password,stored){if(typeof stored!=='string'||!stored.includes('$'))return false;const[salt,expected]=stored.split('$',2),actual=hashPassword(password,salt).split('$')[1];return expected.length===actual.length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(actual));}
const number=v=>v===''||v==null?null:Number(v),text=(v,max=5000)=>typeof v==='string'&&v.trim().length>0&&v.length<=max,safeName=n=>{const b=path.basename(String(n||'upload')).replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,120);return b||'upload';};
async function tx(work){const c=await pool.getConnection();try{await c.beginTransaction();const r=await work(c);await c.commit();return r;}catch(e){await c.rollback();throw e;}finally{c.release();}}
function validateConfiguration(){const required=['DB_HOST','DB_USER','DB_PASSWORD','DB_NAME'];const missing=required.filter(name=>!process.env[name]);if(missing.length)throw Error(`Missing required environment variables: ${missing.join(', ')}.`);if(process.env.DB_PORT&&(!Number.isInteger(Number(process.env.DB_PORT))||Number(process.env.DB_PORT)<1||Number(process.env.DB_PORT)>65535))throw Error('DB_PORT must be a valid TCP port number.');}
async function initialiseDatabase(){validateConfiguration();await pool.query(fs.readFileSync(path.join(ROOT,'database','init.sql'),'utf8'));if(!(await one("SELECT id FROM users WHERE role='ADMIN' LIMIT 1"))){if(!process.env.ACUITY_ADMIN_PASSWORD)throw Error('ACUITY_ADMIN_PASSWORD is required before the initial administrator can be created.');const t=now();await query('INSERT INTO users(id,full_name,email,phone,password_hash,role,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',['admin-001','Acuity Administrator','admin@acuity.local','0000000000',hashPassword(process.env.ACUITY_ADMIN_PASSWORD),'ADMIN',t,t]);}}
const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:'same-origin'}}));const origins=(process.env.APP_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);app.use(cors({origin(o,cb){return(!o||origins.includes(o))?cb(null,true):cb(null,false);},credentials:true}));app.use(express.json({limit:'1mb',type:['application/json','application/*+json']}));app.use(cookieParser());
const fail=(res,status,error)=>res.status(status).json({error}),cookie=()=>({httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',path:'/',maxAge:SESSION_DAYS*86400000});
function auth(role){return async(req,res,next)=>{try{const token=req.cookies.acuity_session;if(!token||typeof token!=='string'||token.length>255)return fail(res,403,'Not found or unauthorized.');const user=await one('SELECT u.*,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?',[token]);if(!user||user.expires_at<now()){if(user)await query('DELETE FROM sessions WHERE token=?',[token]);return fail(res,403,'Not found or unauthorized.');}if(role&&user.role!==role)return fail(res,403,'Not found or unauthorized.');req.user=user;next();}catch(e){next(e);}}}
const storage=multer.diskStorage({destination(req,file,cb){const dir=path.join(UPLOADS,req.params.id);fs.mkdir(dir,{recursive:true},e=>cb(e,dir));},filename(req,file,cb){cb(null,`${crypto.randomUUID()}-${safeName(file.originalname)}`);}}),allowed=new Set(['.pdf','.jpg','.jpeg','.png','.doc','.docx']);
const upload=multer({storage,limits:{fileSize:MAX_UPLOAD_BYTES,files:1},fileFilter(req,file,cb){if(!allowed.has(path.extname(file.originalname).toLowerCase())||/[\\/\0]/.test(file.originalname))return cb(Error('Invalid document file type.'));cb(null,true);}});
app.post('/api/auth/register',async(req,res)=>{const d=req.body||{};if(!text(d.full_name,150)||!text(d.email,254)||!text(d.phone,30)||typeof d.password!=='string'||d.password.length<8)return fail(res,400,'Name, email, phone and an 8-character password are required.');const uid=id('cli'),t=now();try{await query('INSERT INTO users(id,full_name,email,phone,password_hash,date_of_birth,gender,address,city,state,pincode,employment_type,company_name,monthly_income,pan,role,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[uid,d.full_name.trim(),d.email.trim().toLowerCase(),d.phone.trim(),hashPassword(d.password),d.date_of_birth||null,d.gender||null,d.address||null,d.city||null,d.state||null,d.pincode||null,d.employment_type||null,d.company_name||null,number(d.monthly_income),d.pan||null,'CLIENT',t,t]);}catch(e){if(e.code==='ER_DUP_ENTRY')return fail(res,409,'An account with this email already exists.');throw e;}res.status(201).json({id:uid,message:'Registration successful.'});});
app.post('/api/auth/login',async(req,res)=>{const d=req.body||{},user=await one('SELECT * FROM users WHERE email=?',[String(d.email||'').trim().toLowerCase()]);if(!user||!verifyPassword(String(d.password||''),user.password_hash))return fail(res,401,'Invalid email or password.');const token=crypto.randomBytes(32).toString('base64url');await query('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)',[token,user.id,new Date(Date.now()+SESSION_DAYS*86400000).toISOString()]);res.cookie('acuity_session',token,cookie()).json({role:user.role,name:user.full_name});});
app.post('/api/auth/logout',async(req,res)=>{if(req.cookies.acuity_session)await query('DELETE FROM sessions WHERE token=?',[req.cookies.acuity_session]);res.clearCookie('acuity_session',cookie()).json({ok:true});});
app.get('/api/client/profile',auth('CLIENT'),(req,res)=>{const{password_hash,expires_at,...user}=req.user;res.json({user});});
app.put('/api/client/profile',auth('CLIENT'),async(req,res)=>{const d=req.body||{},f=['full_name','phone','date_of_birth','gender','address','city','state','pincode','employment_type','company_name','monthly_income','pan'];if(!text(d.full_name,150)||!text(d.phone,30))return fail(res,400,'Name and phone are required.');await query(`UPDATE users SET ${f.map(x=>`${x}=?`).join(',')},updated_at=? WHERE id=?`,[...f.map(x=>x==='monthly_income'?number(d[x]):(d[x]||null)),now(),req.user.id]);res.json({ok:true});});
app.get('/api/client/applications',auth('CLIENT'),async(req,res)=>res.json({applications:await query('SELECT * FROM loan_applications WHERE user_id=? ORDER BY created_at DESC',[req.user.id])}));
app.post('/api/client/applications',auth('CLIENT'),async(req,res)=>{const d=req.body||{},amount=number(d.loan_amount),tenure=number(d.tenure);if(!text(d.loan_type,100)||!Number.isFinite(amount)||amount<=0||!Number.isInteger(tenure)||tenure<=0||!text(d.purpose,1000))return fail(res,400,'Missing loan information.');const aid=id('app'),an=appNo(),t=now();await tx(async c=>{await c.execute('INSERT INTO loan_applications VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[aid,an,req.user.id,d.loan_type.trim(),amount,number(d.interest_rate),tenure,d.purpose.trim(),number(d.monthly_income),number(d.existing_emi)||0,'PENDING',null,t,t]);await c.execute('INSERT INTO application_status_history VALUES(?,?,?,?,?,?)',[crypto.randomUUID().replace(/-/g,''),aid,'PENDING','Application submitted',req.user.id,t]);});res.status(201).json({id:aid,application_number:an});});
app.get('/api/client/applications/:id',auth('CLIENT'),async(req,res)=>{const application=await one('SELECT * FROM loan_applications WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!application)return fail(res,404,'Not found');res.json({application,history:await query('SELECT * FROM application_status_history WHERE application_id=? ORDER BY created_at DESC',[req.params.id]),documents:await query('SELECT id,application_id,document_type,file_name,verification_status,admin_remarks,created_at FROM application_documents WHERE application_id=? AND user_id=?',[req.params.id,req.user.id])});});
async function owned(req,res,next){if(!(await one('SELECT id FROM loan_applications WHERE id=? AND user_id=?',[req.params.id,req.user.id])))return fail(res,404,'Not found');next();}
async function saveDoc(req,res,name,file){const did=id('doc');await query('INSERT INTO application_documents VALUES(?,?,?,?,?,?,?,?,?)',[did,req.params.id,req.user.id,String(req.body.document_type||'Supporting document').slice(0,100),safeName(name),file,'PENDING',null,now()]);res.status(201).json({id:did,message:'Document uploaded.'});}
app.post('/api/client/applications/:id/documents',auth('CLIENT'),owned,(req,res,next)=>{if(req.is('application/json'))return next();upload.single('file')(req,res,e=>{if(e)return next(e);if(!req.file)return fail(res,400,'A document file is required and must be under 5 MB.');saveDoc(req,res,req.file.originalname,path.relative(ROOT,req.file.path)).catch(next);});},async(req,res)=>{const d=req.body||{},encoded=String(d.content||'').split(',',2).pop(),name=safeName(d.file_name);if(!text(d.content,7000000))return fail(res,400,'A document file is required and must be under 5 MB.');if(!/^[A-Za-z0-9+/=\s]+$/.test(encoded))return fail(res,400,'Invalid document data.');const data=Buffer.from(encoded,'base64');if(!data.length||data.length>MAX_UPLOAD_BYTES)return fail(res,400,'A document file is too large.');if(!allowed.has(path.extname(name).toLowerCase()))return fail(res,400,'Invalid document file type.');const dir=path.join(UPLOADS,req.params.id),stored=`${crypto.randomUUID()}-${name}`;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,stored),data);await saveDoc(req,res,name,path.relative(ROOT,path.join(dir,stored)));});
app.get('/api/client/notifications',auth('CLIENT'),async(req,res)=>res.json({notifications:await query('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC',[req.user.id])}));
app.get('/api/admin/dashboard',auth('ADMIN'),async(req,res)=>res.json({stats:await one("SELECT COUNT(*) clients,(SELECT COUNT(*) FROM loan_applications) applications,(SELECT COUNT(*) FROM loan_applications WHERE status='PENDING') pending,(SELECT COALESCE(SUM(loan_amount),0) FROM loan_applications) total FROM users WHERE role='CLIENT'")}));
app.get('/api/admin/clients',auth('ADMIN'),async(req,res)=>res.json({clients:await query("SELECT u.id,u.full_name,u.email,u.phone,u.employment_type,u.monthly_income,u.created_at,COUNT(a.id) applications FROM users u LEFT JOIN loan_applications a ON a.user_id=u.id WHERE u.role='CLIENT' GROUP BY u.id ORDER BY u.created_at DESC")}));
app.get('/api/admin/clients/:id',auth('ADMIN'),async(req,res)=>{const client=await one("SELECT id,full_name,email,phone,date_of_birth,gender,address,city,state,pincode,employment_type,company_name,monthly_income,pan,role,created_at,updated_at FROM users WHERE id=? AND role='CLIENT'",[req.params.id]);if(!client)return fail(res,404,'Not found');res.json({client,applications:await query('SELECT * FROM loan_applications WHERE user_id=? ORDER BY created_at DESC',[req.params.id])});});
app.delete('/api/admin/clients/:id',auth('ADMIN'),async(req,res)=>{if(!(await one("SELECT id FROM users WHERE id=? AND role='CLIENT'",[req.params.id])))return fail(res,404,'Client not found.');await tx(c=>c.execute('DELETE FROM users WHERE id=?',[req.params.id]));res.json({ok:true});});
app.get('/api/admin/applications',auth('ADMIN'),async(req,res)=>res.json({applications:await query('SELECT a.*,u.full_name,u.email,u.phone FROM loan_applications a JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC')}));
app.get('/api/admin/applications/:id/documents',auth('ADMIN'),async(req,res)=>res.json({documents:await query('SELECT * FROM application_documents WHERE application_id=?',[req.params.id])}));
app.get('/api/admin/applications/:id',auth('ADMIN'),async(req,res)=>{const application=await one('SELECT a.*,u.full_name,u.email,u.phone,u.address,u.city,u.state,u.employment_type,u.monthly_income,u.company_name FROM loan_applications a JOIN users u ON a.user_id=u.id WHERE a.id=?',[req.params.id]);if(!application)return fail(res,404,'Not found');res.json({application,documents:await query('SELECT * FROM application_documents WHERE application_id=?',[req.params.id]),history:await query('SELECT * FROM application_status_history WHERE application_id=? ORDER BY created_at DESC',[req.params.id])});});
app.put('/api/admin/applications/:id/status',auth('ADMIN'),async(req,res)=>{const{status,remarks}=req.body||{};if(!STATUSES.has(status))return fail(res,400,'Invalid status.');const a=await one('SELECT user_id,application_number FROM loan_applications WHERE id=?',[req.params.id]);if(!a)return fail(res,404,'Not found');const t=now();await tx(async c=>{await c.execute('UPDATE loan_applications SET status=?,admin_remarks=?,updated_at=? WHERE id=?',[status,remarks||null,t,req.params.id]);await c.execute('INSERT INTO application_status_history VALUES(?,?,?,?,?,?)',[crypto.randomUUID().replace(/-/g,''),req.params.id,status,remarks||null,req.user.id,t]);await c.execute('INSERT INTO notifications VALUES(?,?,?,?,?,?,?)',[id('note'),a.user_id,req.params.id,'Application status updated',`Your application ${a.application_number} is now ${status}.`,0,t]);});res.json({ok:true});});
app.get('/api/documents/:id/download',auth(),async(req,res)=>{const d=await one('SELECT d.*,a.user_id application_owner FROM application_documents d JOIN loan_applications a ON a.id=d.application_id WHERE d.id=?',[req.params.id]);if(!d||(req.user.role!=='ADMIN'&&d.application_owner!==req.user.id))return fail(res,404,'Not found');const file=path.resolve(ROOT,d.file_path);if(!file.startsWith(`${path.resolve(UPLOADS)}${path.sep}`)||!fs.existsSync(file))return fail(res,404,'Not found');res.download(file,safeName(d.file_name));});
app.use('/api',(req,res)=>fail(res,404,'Not found or unauthorized.'));app.use((req,res,next)=>{const n=path.basename(req.path).toLowerCase();if(path.extname(n)==='.db'||n.startsWith('server.')||['.env','package.json','package-lock.json'].includes(n)||req.path.startsWith('/private_uploads/'))return fail(res,404,'Not found');next();});app.use(express.static(ROOT,{dotfiles:'deny',index:'index.html',fallthrough:true}));app.get(['/','/admin'],(req,res)=>res.sendFile(path.join(ROOT,'index.html')));
app.use((e,req,res,next)=>{if(e instanceof multer.MulterError&&e.code==='LIMIT_FILE_SIZE')return fail(res,400,'A document file is too large.');if(e&&e.message==='Invalid document file type.')return fail(res,400,e.message);if(e&&e.message==='Origin not allowed')return fail(res,403,'Origin not allowed.');console.error('Request failed:',e&&e.message);return fail(res,500,'An unexpected error occurred.');});
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Acuity Finance listening on port ${PORT}`);
});

initialiseDatabase()
  .then(() => {
    console.log('Database initialized successfully');
  })
  .catch((e) => {
    console.error('Database initialization failed:', e.message);
  });

module.exports = {
  app,
  pool,
  initialiseDatabase,
  validateConfiguration,
  hashPassword,
  verifyPassword
};
